/*
Qual a quantidade de crimes de um determinado tipo cometido por sexo e etnia no estado de São Paulo
*/
SELECT  
CAST(truncate(L.LATITUDE, 6) AS DECIMAL(17,6)) AS lat,  
CAST(truncate(L.LONGITUDE, 6) AS DECIMAL(18,6)) AS lng
FROM Ocorrencia O 
INNER JOIN Envolvido E 
ON O.ID_ENVOLVIDO = E.ID_ENVOLVIDO 
INNER JOIN TipoCor TC
ON E.ID_TIPO_COR = TC.ID_TIPO_COR
INNER JOIN TipoSexo TS 
ON E.ID_TIPO_SEXO = TS.ID_TIPO_SEXO 
INNER JOIN TipoRubrica TR
ON O.ID_TIPO_RUBRICA = TR.ID_TIPO_RUBRICA 
INNER JOIN Localizacao L 
ON O.ID_LOCALIZACAO = L.ID_LOCALIZACAO 
WHERE TC.TIPO = 'Preta' 
AND TS.TIPO = 'F' 
AND TR.TIPO = 'Roubo (art. 157)' 
AND O.ANO_BO = 2014 
AND L.LATITUDE is not null 
AND L.LONGITUDE is not null;

/*
Crimes de um determinado tipo em zonas urbanas e zonas rurais
*/
SELECT  
CAST(truncate(L.LATITUDE, 6) AS DECIMAL(17,6)) AS lat,  
CAST(truncate(L.LONGITUDE, 6) AS DECIMAL(18,6)) AS lng
FROM Ocorrencia O 
INNER JOIN Envolvido E 
ON O.ID_ENVOLVIDO = E.ID_ENVOLVIDO 
INNER JOIN TipoRubrica TR
ON O.ID_TIPO_RUBRICA = TR.ID_TIPO_RUBRICA 
INNER JOIN Localizacao L 
ON O.ID_LOCALIZACAO = L.ID_LOCALIZACAO 
INNER JOIN Municipio M 
ON M.ID_MUNICIPIO = L.ID_MUNICIPIO
INNER JOIN TipoZona TZ 
ON M.ID_TIPO_ZONA = TZ.ID_TIPO_ZONA
WHERE O.ANO_BO = 2014 
AND TZ.ID_TIPO_ZONA = 2 
AND TR.ID_TIPO_RUBRICA = 6 
AND L.LATITUDE is not null 
AND L.LONGITUDE is not null;

/*
Crime (rubrica) por indice populacional e por período do dia
*/
SELECT  
CAST(truncate(L.LATITUDE, 6) AS DECIMAL(17,6)) AS lat,  
CAST(truncate(L.LONGITUDE, 6) AS DECIMAL(18,6)) AS lng
FROM Ocorrencia O 
INNER JOIN Envolvido E 
ON O.ID_ENVOLVIDO = E.ID_ENVOLVIDO 
INNER JOIN TipoRubrica TR
ON O.ID_TIPO_RUBRICA = TR.ID_TIPO_RUBRICA 
INNER JOIN Localizacao L 
ON O.ID_LOCALIZACAO = L.ID_LOCALIZACAO 
INNER JOIN Municipio M 
ON M.ID_MUNICIPIO = L.ID_MUNICIPIO
INNER JOIN IndicePopulacional IP 
ON M.ID_INDICE_POPULACIONAL = IP.ID_INDICE_POPULACIONAL
INNER JOIN Tempo T
ON O.ID_TEMPO = T.ID_TEMPO
INNER JOIN Periodo P 
ON T.ID_PERIODO = P.ID_PERIODO 
WHERE O.ANO_BO = 2014 
AND IP.ID_INDICE_POPULACIONAL = 2 
AND TR.ID_TIPO_RUBRICA = 6 
AND P.ID_PERIODO = 2
AND L.LATITUDE is not null 
AND L.LONGITUDE is not null 
AND L.LONGITUDE != 0 
AND L.LATITUDE != 0;
